### ISSUE TITLE
E5099 error in doc-tests when packaging in RPM

### ISSUE THREAD

**Issue by aumars** [bincode-org/virtue#80]
I'm writing a RPM package for 0.0.15 but when the doc-tests is run, there is a recurring E5099 error with `virtue::generate::Generator`.
I'm really not sure what could cause this.

```
   Doc-tests virtue
     Running `/usr/bin/rustdoc --edition=2021 --crate-type lib --crate-name virtue --test src/lib.rs --test-run-directory /builddir/build/BUILD/virtue-0.0.15 -L dependency=/builddir/build/BUILD/virtue-0.0.15/target/rpm/deps -L dependency=/builddir/build/BUILD/virtue-0.0.15/target/rpm/deps --extern proc_macro2=/builddir/build/BUILD/virtue-0.0.15/target/rpm/deps/libproc_macro2-23acc92ef8476791.rlib --extern virtue=/builddir/build/BUILD/virtue-0.0.15/target/rpm/deps/libvirtue-0a192ea2ac9ff29d.rlib -C embed-bitcode=no --error-format human`

running 43 tests
test src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::as_async (line 158) ... FAILED
test src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::body (line 316) ... FAILED
test src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_arg (line 272) ... FAILED
test src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_generic (line 208) ... FAILED
test src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_generic_deps (line 228) ... FAILED
test src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_lifetime (line 140) ... FAILED
test src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_lifetime_deps (line 178) ... FAILED
test src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_return_type (line 291) ... FAILED
test src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_self_arg (line 254) ... FAILED
test src/generate/generate_item.rs - generate::generate_item::GenConst<'a>::with_value (line 61) ... ignored
test src/generate/generate_mod.rs - generate::generate_mod::GenerateMod<'a,P>::add_use (line 32) ... ignored
test src/generate/generate_item.rs - generate::generate_item::GenConst<'a>::with_value (line 47) ... FAILED
test src/generate/generator.rs - generate::generator::Generator::impl_for_other_type (line 65) ... FAILED
test src/generate/generator.rs - generate::generator::Generator::impl_for_with_lifetimes (line 102) ... FAILED
test src/generate/generator.rs - generate::generator::Generator::impl_for_with_lifetimes (line 114) ... FAILED
test src/generate/impl.rs - generate::r#impl::Impl<'a,Generator>::modify_generic_constraints (line 113) ... ignored
test src/generate/impl.rs - generate::r#impl::Impl<'a,P>::generate_const (line 100) ... ignored
test src/generate/generator.rs - generate::generator::Generator::impl_trait_for_other_type (line 79) ... FAILED
test src/generate/impl.rs - generate::r#impl::Impl<'a,P>::generate_fn (line 74) ... ignored
test src/generate/impl.rs - generate::r#impl::Impl<'a,P>::generate_const (line 86) ... FAILED
test src/generate/impl_for.rs - generate::impl_for::ImplFor<'a,P>::generate_const (line 120) ... ignored
test src/generate/impl_for.rs - generate::impl_for::ImplFor<'a,P>::generate_fn (line 132) ... ignored
test src/generate/impl_for.rs - generate::impl_for::ImplFor<'a,P>::impl_type (line 147) ... ignored
test src/generate/impl_for.rs - generate::impl_for::ImplFor<'a,P>::modify_generic_constraints (line 168) ... ignored
test src/generate/stream_builder.rs - generate::stream_builder::StreamBuilder::lifetime (line 108) ... ignored
test src/generate/stream_builder.rs - generate::stream_builder::StreamBuilder::lifetime_str (line 124) ... ignored
test src/lib.rs - (line 26) ... ignored
test src/lib.rs - (line 52) ... ignored
test src/lib.rs - (line 63) ... ignored
test src/parse/attributes.rs - parse::attributes::AttributeLocation::Field (line 27) ... ignored
test src/generate/impl_for.rs - generate::impl_for::ImplFor<'a,P>::generate_const (line 106) ... FAILED
test src/parse/body.rs - parse::body::Fields::delimiter (line 412) ... ok
test src/parse/body.rs - parse::body::Fields::names (line 383) ... ok
test src/parse/body.rs - parse::body::IdentOrIndex (line 546) ... ok
test src/parse/generics.rs - parse::generics::Generic::Const (line 196) ... ok
test src/parse/generics.rs - parse::generics::Generic::Generic (line 187) ... ok
test src/parse/generics.rs - parse::generics::Generic::Lifetime (line 178) ... ok
test src/parse/generics.rs - parse::generics::GenericConstraints::push_constraint (line 532) ... ignored
test src/parse/generics.rs - parse::generics::GenericConstraints::push_parsed_constraint (line 564) ... ignored
test src/parse/generics.rs - parse::generics::Generics (line 10) ... ok
test src/parse/mod.rs - parse::Parse (line 26) ... ignored
test src/parse/generics.rs - parse::generics::GenericConstraints (line 490) ... ok
test src/utils.rs - utils::parse_tagged_attribute (line 13) ... FAILED

failures:

---- src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::as_async (line 158) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generate_item.rs:161:32
  |
6 | let mut generator = Generator::with_name("Foo");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::body (line 316) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generate_item.rs:319:32
  |
6 | let mut generator = Generator::with_name("Foo");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_arg (line 272) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generate_item.rs:275:32
  |
6 | let mut generator = Generator::with_name("Foo");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_generic (line 208) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generate_item.rs:211:32
  |
6 | let mut generator = Generator::with_name("Foo");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_generic_deps (line 228) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generate_item.rs:231:32
  |
6 | let mut generator = Generator::with_name("Foo");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_lifetime (line 140) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generate_item.rs:143:32
  |
6 | let mut generator = Generator::with_name("Foo");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_lifetime_deps (line 178) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generate_item.rs:181:32
  |
6 | let mut generator = Generator::with_name("Foo");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_return_type (line 291) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generate_item.rs:294:32
  |
6 | let mut generator = Generator::with_name("Foo");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_self_arg (line 254) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generate_item.rs:257:32
  |
6 | let mut generator = Generator::with_name("Foo");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generate_item.rs - generate::generate_item::GenConst<'a>::with_value (line 47) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generate_item.rs:50:32
  |
6 | let mut generator = Generator::with_name("Bar");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generator.rs - generate::generator::Generator::impl_for_other_type (line 65) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generator.rs:68:32
  |
6 | let mut generator = Generator::with_name("Baz");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generator.rs - generate::generator::Generator::impl_for_with_lifetimes (line 102) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generator.rs:105:32
  |
6 | let mut generator = Generator::with_name("Bar");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generator.rs - generate::generator::Generator::impl_for_with_lifetimes (line 114) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generator.rs:117:32
  |
6 | let mut generator = Generator::with_name("Bar").with_lifetime("a");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/generator.rs - generate::generator::Generator::impl_trait_for_other_type (line 79) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/generator.rs:82:32
  |
6 | let mut generator = Generator::with_name("Baz");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/impl.rs - generate::r#impl::Impl<'a,P>::generate_const (line 86) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/impl.rs:89:32
  |
6 | let mut generator = Generator::with_name("Bar");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/generate/impl_for.rs - generate::impl_for::ImplFor<'a,P>::generate_const (line 106) stdout ----
error[E0599]: no function or associated item named `with_name` found for struct `virtue::generate::Generator` in the current scope
 --> src/generate/impl_for.rs:109:32
  |
6 | let mut generator = Generator::with_name("Bar");
  |                                ^^^^^^^^^ function or associated item not found in `Generator`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/utils.rs - utils::parse_tagged_attribute (line 13) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at library/proc_macro/src/bridge/client.rs:311:17:
procedural macro API is used outside of a procedural macro
stack backtrace:
   0:     0x55fc12716fbc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5134e2ea5207acc3
   1:     0x55fc1273759c - core::fmt::write::h65bebc52b764970f
   2:     0x55fc12714d4d - std::io::Write::write_fmt::h637412203b809dd3
   3:     0x55fc12716da5 - std::sys_common::backtrace::print::hd6011497b00f2a53
   4:     0x55fc12718323 - std::panicking::default_hook::{{closure}}::h3395cb502e3cfe26
   5:     0x55fc12718045 - std::panicking::default_hook::h978d6d2a22a58f68
   6:     0x55fc127188b5 - std::panicking::rust_panic_with_hook::h4ed8681e16866d02
   7:     0x55fc12718756 - std::panicking::begin_panic_handler::{{closure}}::h63ffbddc87fef334
   8:     0x55fc127174f6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6782604550ca104f
   9:     0x55fc127184f2 - rust_begin_unwind
  10:     0x55fc126e2d05 - core::panicking::panic_fmt::hfe4d8ad47b7b3131
  11:     0x55fc126f27c1 - <proc_macro::TokenStream as core::str::traits::FromStr>::from_str::ha2ad5cbd4b96d6f2
  12:     0x55fc126ece82 - core::str::<impl str>::parse::ha2b746fbe30b51ec
                               at /builddir/build/BUILD/rustc-1.74.1-src/library/core/src/str/mod.rs:2312:9
  13:     0x55fc126ece82 - proc_macro2::imp::<impl core::convert::From<proc_macro2::imp::TokenStream> for proc_macro::TokenStream>::from::h8155756001e02de8
                               at /usr/share/cargo/registry/proc-macro2-1.0.70/src/wrapper.rs:142:63
  14:     0x55fc126e4497 - <T as core::convert::Into<U>>::into::h678800a3a82c73bc
  15:     0x55fc126e5a50 - rust_out::main::_doctest_main_src_utils_rs_13_0::parse_token_stream_group::hb6e4d0435185d81b
  16:     0x55fc126e52f2 - rust_out::main::_doctest_main_src_utils_rs_13_0::haa21f097e17a59aa
  17:     0x55fc126e52c6 - rust_out::main::h7e7eb00290a7202e
  18:     0x55fc126e3b93 - core::ops::function::FnOnce::call_once::h1589f53caba97b4d
  19:     0x55fc126e3936 - std::sys_common::backtrace::__rust_begin_short_backtrace::h12542ac770b5c251
  20:     0x55fc126e3989 - std::rt::lang_start::{{closure}}::h9f9f3177c1931588
  21:     0x55fc12712a7b - std::rt::lang_start_internal::h7aeec23a93e24b8f
  22:     0x55fc126e3967 - std::rt::lang_start::h28a087d150a1b58a
  23:     0x55fc126e5c95 - main
  24:     0x700515542b8a - __libc_start_call_main
  25:     0x700515542c4b - __libc_start_main_alias_2
  26:     0x55fc126e3425 - _start
  27:                0x0 - <unknown>



failures:
    src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::as_async (line 158)
    src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::body (line 316)
    src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_arg (line 272)
    src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_generic (line 208)
    src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_generic_deps (line 228)
    src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_lifetime (line 140)
    src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_lifetime_deps (line 178)
    src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_return_type (line 291)
    src/generate/generate_item.rs - generate::generate_item::FnBuilder<'a,P>::with_self_arg (line 254)
    src/generate/generate_item.rs - generate::generate_item::GenConst<'a>::with_value (line 47)
    src/generate/generator.rs - generate::generator::Generator::impl_for_other_type (line 65)
    src/generate/generator.rs - generate::generator::Generator::impl_for_with_lifetimes (line 102)
    src/generate/generator.rs - generate::generator::Generator::impl_for_with_lifetimes (line 114)
    src/generate/generator.rs - generate::generator::Generator::impl_trait_for_other_type (line 79)
    src/generate/impl.rs - generate::r#impl::Impl<'a,P>::generate_const (line 86)
    src/generate/impl_for.rs - generate::impl_for::ImplFor<'a,P>::generate_const (line 106)
    src/utils.rs - utils::parse_tagged_attribute (line 13)

test result: FAILED. 8 passed; 17 failed; 18 ignored; 0 measured; 0 filtered out; finished in 1.47s

error: doctest failed, to rerun pass `--doc`
error: 1 target failed:
    `--doc`
error: Bad exit status from /var/tmp/rpm-tmp.xuI2rU (%check)
    Bad exit status from /var/tmp/rpm-tmp.xuI2rU (%check)
```

**Comment by VictorKoenders** [comment]
If you're running a test, you need to enable the `proc-macro2` feature. This is because the `proc-macro` stuff can't easily be constructed
